config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'articles#index'

  resources :articles, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    def index
        @articles = Article.all
    end

    def show
        @article = Article.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/index.html.erb
<div class="container">
  <div class="tabs">
    <div class="tabs_item active">
      新着記事一覧
    </div>
    <div class="tabs_item">
      タイムライン
    </div>
  </div>

  <% @articles.each do |article| %>
    <%= link_to article_path(article) do %>
      <div class="card">
        <div class="card_image">
          <%= image_tag 'eyecatch1.png' %>
        </div>
        <div class="card_content">
          <div class="card_title">
            <%= article.title %>
          </div>
          <div class="card_heart">
            <%= image_tag 'heart.svg' %>
            <span>23</span>
          </div>
          <div class="card_detail">
            <%= image_tag 'default-avatar.png' %>
            <div>
              <p>cohki0305</p>
              <p>2020/4/16</p>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/articles/show.html.erb
<div class="article">
  <h1 class="article_title"><%= @article.title %></h1>
  <div class="article_detail">
    <%= image_tag 'default-avatar.png' %>
    <div>
      <p>cohki0305</p>
      <p>2020/4/16</p>
    </div>
  </div>
  <div class="article_content">
    <%= @article.content %>
  </div>
  <div class="article_heart">
    <%= image_tag 'heart.svg' %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  </head>

  <body>
    <header class="header">
      <p class="header_pageTitle">新着記事</p>
      <div class="dropdown">
        <%= image_tag 'default-avatar.png', class: 'header_avatar dropbtn' %>
        <div class="dropdown-content">
          <a href="#">プロフィール</a>
          <a href="#">ログアウト</a>
        </div>
      </div>
    </header>
    <%= yield %>
  </body>
</html>